/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaRouteImport } from './routes/ca'
import { Route as HowRouteImport } from './routes/how'
import { Route as PactRouteImport } from './routes/pact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaRoute = CaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const PactRoute = PactRouteImport.update({
  id: '/pact',
  path: '/pact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/how': typeof HowRoute
  '/pact': typeof PactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/how': typeof HowRoute
  '/pact': typeof PactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/how': typeof HowRoute
  '/pact': typeof PactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ca' | '/how' | '/pact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ca' | '/how' | '/pact'
  id: '__root__' | '/' | '/ca' | '/how' | '/pact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaRoute: typeof CaRoute
  HowRoute: typeof HowRoute
  PactRoute: typeof PactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca': {
      id: '/ca'
      path: '/ca'
      fullPath: '/ca'
      preLoaderRoute: typeof CaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pact': {
      id: '/pact'
      path: '/pact'
      fullPath: '/pact'
      preLoaderRoute: typeof PactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaRoute: CaRoute,
  HowRoute: HowRoute,
  PactRoute: PactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
